server:
  port: 8099

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/project2
    username: 
    password: 

#    CI/CD용 EC2 DB
#    url: jdbc:mysql://ec2-mysql-db1.c6l0kqlbscuy.ap-northeast-2.rds.amazonaws.com:3306/project2
#    username:
#    password:

  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true

  thymeleaf:
    cache: false
#    check-template-location: true
#    prefix: classpath:/templates/
#    suffix: .html
#    enabled: true

  profiles:
    include: oauth
    
# workplace, works api
navar.api.client-id: 
navar.api.client-secret: 

